spring:
  datasource:
    #The DB name cannot contains hyphen character "-", you should use underscore character "_".
    url: jdbc:mysql://localhost:3307/practice10-transaction-simple?useSSL=false
    username: user
    password: user
    #HikariCP: the connection pool framework: http://www.baeldung.com/hikaricp
    hikari:
      pool-name: practice10-transaction-simple-pool

    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
#    show-sql: true
    properties:
      hibernate.format_sql: true

      # This config must match with Dialect config in TransactionalOutboxConfig.persistor()
      hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect

    # Avoid accidental performance issue: https://github.com/spring-projects/spring-boot/issues/7107
    open-in-view: false
    hibernate:
      ddl-auto: update

  sql:
    init:
      #Account for running schema scripts
      username: root
      password: root